import type { Metadata } from "next";
import "./globals.css";
import { poiret_one, raleway } from "@lib/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.className} ${poiret_one.className}`}>
      <body>{children}</body>
    </html>
  );
}
